### ISSUE TITLE
Separate sample app

### ISSUE THREAD

**Issue by jasperblues** [valentinradu/Helm#5]
Excellent lib. Not sure about others, but it would be useful for me if there was a separate standalone sample (either in the repo or outside) to hasten getting started. 

Playground was useful.

**Comment by valentinradu** [comment]
Will do!

**Comment by ConfusedVorlon** [comment]
yes please!
Also, it looks like this is set up in some way to be used as a playground. Could you add some docs on how to do that?

I ended up just creating a new app and using the individual files to test/play

**Comment by anasimtiaz** [comment]
+1 to this

**Comment by priyankpat** [comment]
I've created a [sample app](https://github.com/priyankpat/HelmSamples) with the examples. Tested on iPhone and Mac.

**Comment by valentinradu** [comment]
@priyankpat That looks great! If you can add a license to it (e.g. MIT) I'm ready to link it in the README.md

**Comment by priyankpat** [comment]
@valentinradu I've made the necessary changes to the repo.

**Comment by valentinradu** [comment]
@priyankpat Thank you! Added right under `Usage`
