### ISSUE TITLE
Is Navigation View supported on iPad (columns mode) ?

### ISSUE THREAD

**Issue by ConfusedVorlon** [valentinradu/Helm#6]
The NavigationViewExample doesn't work on iPad. 
It shows the error 
"No seque from a presented fragment to b"

(when you show one city, then try to shift to another)

I'm unclear if this is a limitation on the library - or just that some different edge definitions are required)

**Comment by valentinradu** [comment]
@ConfusedVorlon This is because the graph was does not have a segue between `b` and another instance of `b`, which is required on iPad since the navigation is not: `present -> dismiss -> present`, but `present -> present -> present`. Aka you don't need to dismiss `b` to present another instance of it like you'd do on a normal master - details list.

**Comment by valentinradu** [comment]
Unrelated to the library itself, more related to the usage. Hope it helps!

**Comment by ConfusedVorlon** [comment]
thanks for the response.
How would you code the b -> b ?

I tried
```

        @StateObject private var _helm: Helm = try! Helm(nav: [
            PlaygroundSegue(.a => .b).makeDismissable(),
            PlaygroundSegue(.b => .b),
        ])
```

but that didn't work!

thanks

**Comment by valentinradu** [comment]
```swift
@StateObject private var _helm: Helm = try! Helm(nav: [
    PlaygroundSegue(.a => .b).makeDismissable(),
    PlaygroundSegue(.b => .b),
])
```

This should work, I've just tested it myself.

**Comment by ConfusedVorlon** [comment]
Doh! - copying error on my part. Thanks for your patience :)

**Comment by valentinradu** [comment]
Also, for iPad, you might want to make the first segue auto instead of dismissable, since there's always going to be a detail view presented! It's more like a tab than a master detail.
