### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jasperblues** [valentinradu/Helm#7]
Traditional analytics tools don't provide graph analytics. Helm would enable this. 

When enabled we could record paths taken by the user, then: 

* Identify common paths. If one exists already, recommend the shorter path to the user. 
* If one doesn't exist, give this feedback to the app developer <-- common navigation paths / usages to improve UX. We could measure how this affects retention. 

Also say there was an on-boarding process, with X screens to complete. We measure the total time, and time on each screen. Then optimize to lessen the time on each screen. We could measure the conversion rate from download -> sign up. 

--
**One More:**
If the app has a free version, and there was a desire to convert customers to the super-duper version analyze what paths users most commonly take to get to the 'sign me up for super-duper' screen, and highlight those paths. 

^-- So yeah, graph analytics would be a cool feature, especially for the UX folks.

**Comment by valentinradu** [comment]
That's actually a great idea on its own (leaving aside Helm for a sec). I also think it might be possible with Helm as we speak, but yeah, I suppose the nav graph should probs be replicated. I'll think about it, but the idea is sound in its own (I don't seen it as a Helm feature, but I'm considering exposing the required data for other third parties to use)
