### ISSUE TITLE
(54, 32) Cannot convert value of type 'DirectedEdge<AppFragment>' to expected element type 'PathEdge<AppFragment>'

### ISSUE THREAD

**Issue by jasperblues** [valentinradu/Helm#8]
Sorry, not sure correct place to ask advice (if you like I can create a StackOverflow tag). Its probably user error, however I tried to follow the README to instantiate at a given path: 

```swift
let helm = try! Helm(nav: AppFragment.segues, path: [
    AppFragment.navigation => AppFragment.spaces
])
```

with Fragments: 

```swift
enum AppFragment: Fragment {
    case navigation
    case profile
    case connections
    case spaces
    case notifications
    case spaceMessage

    static let edges = Set<DirectedEdge<AppFragment>>()
    .union(.navigation => [.profile, .connections, .spaces, .notifications])
    .union(.spaces => [.spaceMessage])

    static let segues = Set(edges.map { (edge: DirectedEdge<AppFragment>) -> Segue<AppFragment> in
        switch edge {

        case AppFragment.navigation => AppFragment.profile:
            return Segue(edge, style: .hold, dismissable: true, auto: true)
        case AppFragment.navigation => AppFragment.connections:
            return Segue(edge, style: .hold, dismissable: true, auto: true)
        case AppFragment.navigation => AppFragment.spaces:
            return Segue(edge, style: .hold, dismissable: true, auto: true)
        case AppFragment.navigation => AppFragment.notifications:
            return Segue(edge, style: .hold, dismissable: true, auto: true)
        case AppFragment.spaces => AppFragment.spaceMessage:
            return Segue(edge, style: .hold, dismissable: true)
        default:
            // the default is style: .pass, auto: false, dismissable: false
            return Segue(edge)
        }
    })
}
```

And I receive: 

`(54, 32) Cannot convert value of type 'DirectedEdge<AppFragment>' to expected element type 'PathEdge<AppFragment>'`

I looked at how tests were doing it, but they're using the `TestGraph()` function, which I don't quite grok yet.

**Comment by valentinradu** [comment]
That's super weird, the above compiles without an issue on my machine 🤔

**Comment by jasperblues** [comment]
I installed via SPM. I can probably share the project, as there's nothing proprietary in here. Just some scaffolding to test things out before adding Helm on a large project. 

(This could probably be the sample app with a few changes).

**Comment by valentinradu** [comment]
Sure, if you can share it that would be great. I'd have a look.

**Comment by jasperblues** [comment]
> Sure, if you can share it that would be great. I'd have a look.

Will just set it up to publish publicly. 

In the meantime, I can say that it works like this; 

```swift
let helm = try! Helm(nav: AppFragment.segues, path: [
        PathEdge(AppFragment.navigation => AppFragment.spaces, sourceId: nil as String?, targetId: nil as String?)
    ])
```

I'm pulling in Helm via SPM main branch. Path is expecting a `PathEdge` not `DirectedEdge` argument in this branch. 

However, I expected to appear on a `Spaces` tab, and it still launches onto a random tab. Either my graph is set up incorrectly, or there's a bug (probably former).

**Comment by jasperblues** [comment]
Update: Starting path worked after turning `auto` off in the graph above. 

All is clear now, though I think: 

* The of instantiating with a path could be more terse (some shortcut, since it would be a common pattern. Perhaps at least make the sourceId, and targetId args have a nil default). 
* Doesn't match the docs. 

_(ps: closed the issue. Not sure if you folks submitting to close or control that yourself?)_

**Comment by valentinradu** [comment]
Ah, alright, I was not paying attention, the problem is the initial path not the segues. Sorry about that. And yes, indeed, it requires a `PathEdge` not a `DirectedEdge`.  Most of the times tho, the path comes from Helm, gets stored and then set back to Helm in other sessions (which means you don't have to manually recreate it). However, point taken, it is rather dull to create.

**Comment by jasperblues** [comment]
With these extensions we can have it work as described in the README: 

```swift
import Foundation
import Helm
import Collections

extension PathEdge {
    static func from(_ directedEdge: DirectedEdge<N>) -> PathEdge<N> {
        return PathEdge<N>(directedEdge, sourceId: nil as String?, targetId: nil as String?)
    }
}

extension Helm {
    public convenience init(nav: HelmGraph, path: [DirectedEdge<N>]) throws {
        try self.init(nav: nav, path: HelmPath(path.map { PathEdge.from($0) }))
    }
}
```
